### ISSUE TITLE
Update css to increase usability of the Flemish Standard DMP 

### ISSUE THREAD

**Issue by maarten-vermeyen** [DMPbelgium/roadmap#57]
I’ve been testing the new FWO template in https://preview.dmponline.be/ (now also in production) and I have a styling suggestion. The new template contains a default answer with a predefined table. As the table has a large number of columns, it would be beneficial if we could maximize the use of horizontal space. The css currently contains the following rules for the container class: 

``` css
@media (min-width: 768px) {
.container {
  width:750px
}
}
@media (min-width: 992px) {
.container {
  width:970px
}
}
@media (min-width: 1200px) {
.container {
  width:100%;
}
}
```
Changing this would result in the application making better use of the horizontal space, benefitting not only this specific case, but the editing of DMP’s in general (e.g. more room for guidance and comments column, resulting in less scrolling).

``` css
.container {
  width: 100%;
}
````
If others would agree, I would like to propose this change for inclusion in future update. Also see https://github.com/DMPRoadmap/roadmap/wiki/Branding for guidelines on applying custom stylesheets without modifying the core DMPRoadmap stylesheets.
